### ISSUE TITLE
libvorbisenc missing in Windows

### ISSUE THREAD

**Issue by mattgwwalker** [TeamPyOgg/PyOgg#40]
Hi Zuzu-Typ,

From the work I did on the build process for wheels (#39), I noticed that the current Windows wheels are missing `libvorbisenc.dll`.  I suspect that they were just forgotten :o) but it might be worth adding them into the new `pyogg/libs` directory.  The `setup.py` file is ready for them as soon as they're added.

Cheers,

Matthew

**Comment by Zuzu-Typ** [comment]
Hi Matthew,

for some reason the people at Xiph.org decided that it would be a good idea to have different library featuresets on different operating systems.
On Windows, there is no `libvorbisenc` as it's already contained by `libvorbis.dll`.

The library is not loaded correctly anyways so that's why it was missing.

I've already created a fix.

Cheers
--Zuzu_Typ--
